use_frameworks!

platform :ios, '8.0'

target 'LTNetMonitor_Example' do
  pod 'LTNetMonitor', :path => '../'

  target 'LTNetMonitor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
